"""Add enums to tickets

Revision ID: 2ddc09356c14
Revises: f919f65ef6f8
Create Date: 2026-09-21 01:01:45.526930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddc09356c14'
down_revision = 'f919f65ef6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum(), nullable=False))
        batch_op.drop_column('validated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
