"""new vehicle model

Revision ID: 625ab12db2f8
Revises: 71d9f5e752ad
Create Date: 2026-09-23 22:49:08.197654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625ab12db2f8'
down_revision = '71d9f5e752ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('vin', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_created_at'))

    op.drop_table('vehicle')
    # ### end Alembic commands ###
