"""Add enums to tickets

Revision ID: 7dab121fef9f
Revises: 2ddc09356c14
Create Date: 2026-09-21 01:02:54.374432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dab121fef9f'
down_revision = '2ddc09356c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ticket')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum(), nullable=False))
        batch_op.drop_column('validated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')

    op.create_table('_alembic_tmp_ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('comments', sa.VARCHAR(length=300), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
