"""empty message

Revision ID: 97d04e0906fd
Revises: d2221b1be8da
Create Date: 2026-09-29 15:41:59.630572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d04e0906fd'
down_revision = 'd2221b1be8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_status', sa.Enum('ADMIN', 'COMPANY_DRIVER', 'CONTRACTED_DRIVER', 'THIRD_PARTY', name='employeetype'), server_default='THIRD_PARTY', nullable=False))
        batch_op.drop_column('permission_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_level', sa.VARCHAR(length=17), server_default=sa.text("'THIRD_PARTY'"), nullable=False))
        batch_op.drop_column('employee_status')

    # ### end Alembic commands ###
